### ISSUE TITLE
iot_button double_click (CON-1293)

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-matter#1042]
Trying the generic_switch example, I noticed that the BUTTON_DOUBLE_CLICK event is not executed.

I believe the problem is related to version 2.5.0 of the espressiff/button dependency

Has anyone encountered the same problem?

**Comment by shubhamdp** [comment]
`BUTTON_DOUBLE_CLICK` event is under `CONFIG_GENERIC_SWITCH_TYPE_LATCHING`, did you change the switch type to latching?

**Comment by shubhamdp** [comment]
@stefano055415 I cut-pasted the code snippet that you provided and run the code on C3, with iot_button version 2.5.0, and I was able to see the double click event.

esp-idf: v5.2.2
SoC: ESP32-C3 with onboard push button (GPIO_9)

<details>
<summary>less dependencies.lock</summary>

```
dependencies:
  espressif/button:
    component_hash: 4d3ea5c1b7a4926c9d027e0bde0188207dadb0d1841d1cec2524f0cddd22f779
    source:
      service_url: https://api.components.espressif.com/
      type: service
    version: 2.5.0
```
</details>


<img width="435" alt="Screenshot 2024-08-09 at 08 55 28" src="https://github.com/user-attachments/assets/7ec657b7-f3ba-4f8f-80fd-7939e1864885">


Can you please help with more details (idf revision, chip, io number, any other details that would help debug this), or can you try with newer iot_button version?
