### ISSUE TITLE
esp-cryptoauthlib unable to build after idf 5.0.1 upgrade (CON-440)

### ISSUE THREAD

**Issue by JonathanWitthoeft** [espressif/esp-matter#344]
Perhaps there is some conflict with cryptoauth lib and the matter sdk, as I can build fine in idf 5.0.1. This is in follow up to this issue, as there are many similarities:
https://github.com/espressif/esp-idf/issues/11061

I have attached the full modified [sdkconfig](https://github.com/espressif/esp-matter/files/11324062/sdkconfig.txt) file for the [examples/light](https://github.com/espressif/esp-matter/tree/main/examples/light) project, however simple steps to reproduce are explained below.

**Steps to reproduce.**
I was able to reproduce this error with the [examples/light](https://github.com/espressif/esp-matter/tree/main/examples/light) project by doing the following.

1) Modify the [main/idf_component.yml](https://github.com/espressif/esp-matter/blob/main/examples/light/main/idf_component.yml) to include the espressif/esp-cryptoauthlib dependency:
```
dependencies:
  espressif/cmake_utilities:
    version: 0.*
    rules: # will add "optional_component" only when all if clauses are True
      - if: "idf_version >=5.0"
      - if: "target in [esp32c2]"
  espressif/esp-cryptoauthlib: "^3.3.1"
```

2) Unset both `BT_NIMBLE_CRYPTO_STACK_MBEDTLS` and `MBEDTLS_ECP_RESTARTABLE` in menuconfig
(If not: `MBEDTLS_ECP_RESTARTABLE defined, but it cannot coexist with an alternative or PSA-based ECP implementation`)

3) In menuconfig set the following esp-cryptoauth configuration:
```
+#
+# esp-cryptoauthlib
+#
+# CONFIG_ATECC608A_TNG is not set
+# CONFIG_ATECC608A_TFLEX is not set
+CONFIG_ATECC608A_TCUSTOM=y
+CONFIG_ATCA_MBEDTLS_ECDSA=y
+CONFIG_ATCA_MBEDTLS_ECDSA_SIGN=y
+CONFIG_ATCA_MBEDTLS_ECDSA_VERIFY=y
+CONFIG_ATCA_I2C_SDA_PIN=16
+CONFIG_ATCA_I2C_SCL_PIN=17
+CONFIG_ATCA_I2C_ADDRESS=0x6A
+CONFIG_ATCA_I2C_BAUD_RATE=100000
+# end of esp-cryptoauthlib
```

**This will lead you to the following error:**
```
In function 'atcac_sw_sha1_finish':
cc1: error: 'atcac_sw_sha2_256_finish' accessing 32 bytes in a region of size 20 [-Werror=stringop-overflow=]
cc1: note: referencing argument 2 of type 'uint8_t *' {aka 'unsigned char *'}
esp-cryptoauthlib/cryptoauthlib/lib/mbedtls/atca_mbedtls_wrap.c:419:5: note: in a call to function 'atcac_sw_sha2_256_finish'
  419 | int atcac_sw_sha2_256_finish(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
```
